### PR TITLE
pin Dockerfile base image to a sha digest

### PR DESCRIPTION
**Pull request by tuminoid**
Pin centos base image by sha digest.

### CODE REVIEW

**Review by kashifest — DISMISSED** [review]

**Comment by tuminoid** [comment]
/hold

Want to get everyone's opinion if this is OK or not. Pinning has pros/cons.

**Comment by elfosardo** [comment]
I'm ok moving this to centos9, was obviosuly forgotten
I'm not keen to pin the base image, AFAIK it's not a good practice
I believe pinning to a specific version was already discussed and rejected
would probably be a discussion for a broader audience

**Comment by tuminoid** [comment]
> I'm not keen to pin the base image, AFAIK it's not a good practice 

It has pros and cons. It is good for rebuildability, avoiding accidental breakage, securing the supply chain etc. On the other hand, it requires uplifting and if not automated or otherwise done in orderly fashion, then you don't get the vulnerability fixes automatically. Non-pinned dependencies (including base OS, base images) are flagged by scanning software etc, so I'd say the industry is or is moving to agreeing it IS a best practice.

https://github.com/ossf/scorecard/blob/c40859202d739b31fd060ac5b30d17326cd74275/docs/checks.md#pinned-dependencies

We have already pinned most of the images, and Go.mod files do the pinning automatically, same with NPM. We have only few centos and ubuntu base OS image unpinned at this point, plus Python dependencies and some shell installers. This is all also in line with CAPI ecosystem.

> I believe pinning to a specific version was already discussed and rejected would probably be a discussion for a broader audience

This discussion predates my involvement in Metal3. Would you remember where and with whom it was discussed last time around?

> I'm ok moving this to centos9, was obviosuly forgotten 

Check. I'm OK for now to just uplift to `centos9` and remove the pinning from this PR, let's discuss the topic in some upcoming forum.

**Comment by tuminoid** [comment]
I've separated the `stream9` uplift to https://github.com/metal3-io/ironic-hardware-inventory-recorder-image/pull/21
/work-in-progress

**Comment by elfosardo** [comment]
> > I'm not keen to pin the base image, AFAIK it's not a good practice
> 
> It has pros and cons. It is good for rebuildability, avoiding accidental breakage, securing the supply chain etc. On the other hand, it requires uplifting and if not automated or otherwise done in orderly fashion, then you don't get the vulnerability fixes automatically. Non-pinned dependencies (including base OS, base images) are flagged by scanning software etc, so I'd say the industry is or is moving to agreeing it IS a best practice.
> 
> https://github.com/ossf/scorecard/blob/c40859202d739b31fd060ac5b30d17326cd74275/docs/checks.md#pinned-dependencies

Interesting reading, thanks.
I just want to clarify that I'm not against pinning the base image, just skeptical about the pros, it also requires some automation in place to keep things smooth and up-to-date, so I'd rather see this decision being discussed thoroughly before moving forward with it.

> We have already pinned most of the images, and Go.mod files do the pinning automatically, same with NPM. We have only few centos and ubuntu base OS image unpinned at this point, plus Python dependencies and some shell installers. This is all also in line with CAPI ecosystem.

It's very different pinning GO or even python dependencies, and OS images.
We're actually pondering about pinning RPMs or python libraries (in case we switch to source code), but again probably we need an extensive discussion about this.

> 
> > I believe pinning to a specific version was already discussed and rejected would probably be a discussion for a broader audience
> 
> This discussion predates my involvement in Metal3. Would you remember where and with whom it was discussed last time around?

I don't remember the details, it was some time ago and the main concern was around the frequency of the updates, if I remember correctly.

> 
> > I'm ok moving this to centos9, was obviosuly forgotten
> 
> Check. I'm OK for now to just uplift to `centos9` and remove the pinning from this PR, let's discuss the topic in some upcoming forum.

**Comment by tuminoid** [comment]
/unhold

Based on the Team Meetup discussion, pinning should be fine.

**Comment by tuminoid** [comment]
/cc @Rozzii @zaneb 
LGTM or comments please?

**Comment by tuminoid** [comment]
Apparently `centos:stream9` tags are being cleaned up in quay and cannot be relied on. For example this SHA has already been deleted.

Hence I'm going to close this PR, and revert the one already merged in `mariadb-image` as well.

/close

**Pull request closed without merging**
